baseURL = "http://angli-datadog.s3-website-us-east-1.amazonaws.com"
languageCode = "en-us"
title = "DD Project"

[[deployment.targets]]
name = "awsbucket"
URL = "s3://angli-datadog/?region=us-east-1"
